CREATE DATABASE customer_behaviour;
USE customer_behaviour;
SELECT * FROM customer_shopping_behaviour LIMIT 10;

/*1.what is the total revenue generated by male gc female customers?*/
SELECT gender,SUM(purchase_amount) AS revenue from customer_shopping_behaviour group by gender;

/*2.which customer used a discount but still spent more than the average purchase amount*/
SELECT customer_id, purchase_amount 
FROM customer_shopping_behaviour 
WHERE discount_applied = 'Yes' 
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_shopping_behaviour);

/*3.which are the top 5 products with the highest average review rating*/
SELECT 
    item_purchased, 
    ROUND(AVG(review_rating), 2) AS avg_review_rating
FROM 
    customer_shopping_behaviour
GROUP BY 
    item_purchased
ORDER BY 
    avg_review_rating DESC
LIMIT 5;


/*4.Compare the average Purchase Amount between Standard and Express Shipping*/
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM 
    customer_shopping_behaviour
WHERE 
    shipping_type IN ('Standard', 'Express')
GROUP BY 
    shipping_type;
    
    
    
/*5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.    */
SELECT subscription_status,
       count(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_shopping_behaviour
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;
/*6. Which 5 products have the highest percentage of purchases with discounts applied?*/

SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer_shopping_behaviour
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on total previous purchases
WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_shopping_behaviour
)
SELECT 
    customer_segment,
    COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment
ORDER BY "Number of Customers" DESC;
-- Q8. Find the top 3 most purchased products within each category
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer_shopping_behaviour
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;

-- Q9. Check if repeat buyers (more than 5 previous purchases) are likely to subscribe
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers,
    ROUND(
        100.0 * COUNT(customer_id) / SUM(COUNT(customer_id)) OVER (), 
        2
    ) AS percentage
FROM customer_shopping_behaviour
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_buyers DESC;

-- Q10. Calculate the total revenue contributed by each age group
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer_shopping_behaviour
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Q11. Analyze how customer loyalty (segment) relates to subscription behavior
WITH customer_type AS (
    SELECT 
        customer_id,
        subscription_status,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_shopping_behaviour
)
SELECT 
    customer_segment,
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(
        100.0 * COUNT(customer_id) / SUM(COUNT(customer_id)) OVER (PARTITION BY customer_segment),
        2
    ) AS percentage_within_segment
FROM customer_type
GROUP BY customer_segment, subscription_status
ORDER BY customer_segment, subscription_status;







